export const ALLOW_SITE_LIST = [
	{
		id: 1,
		moribsetname: 'Capstone Design',
		allowedsites: ['(150) 침착맨 - Youtube 1', '가재맨 - Youtube 1', '구글'],
	},
	{ id: 2, moribsetname: 'Capstone Design 2', allowedsites: ['(150) 침착맨 - Youtube 2', '네이버'] },
	{ id: 3, moribsetname: '캡스톤 디자인', allowedsites: ['(150) 침착맨 - Youtube 3'] },
	{ id: 4, moribsetname: 'ID 워크숍 ID 워크숍 ID 워크숍 ID 워크숍', allowedsites: ['(150) 침착맨 - Youtube 4'] },
	{ id: 5, moribsetname: 'Capstone Design 5', allowedsites: ['(150) 침착맨 - Youtube 5'] },
	{ id: 6, moribsetname: 'Capstone Design 6', allowedsites: ['(150) 침착맨 - Youtube 6'] },
	{ id: 7, moribsetname: 'Capstone Design 7', allowedsites: ['(150) 침착맨 - Youtube 7'] },
	{ id: 8, moribsetname: 'Capstone Design 8', allowedsites: ['(150) 침착맨 - Youtube 8'] },
	{ id: 9, moribsetname: 'Capstone Design 9', allowedsites: ['(150) 침착맨 - Youtube 9'] },
	{ id: 10, moribsetname: 'Capstone Design 10', allowedsites: ['(150) 침착맨 - Youtube 10'] },
	{ id: 11, moribsetname: 'Capstone Design 11', allowedsites: ['(150) 침착맨 - Youtube 11'] },
	{ id: 12, moribsetname: 'Capstone Design 12', allowedsites: ['(150) 침착맨 - Youtube 12'] },
	{ id: 13, moribsetname: 'Capstone Design 13', allowedsites: ['(150) 침착맨 - Youtube 13'] },
	{ id: 14, moribsetname: 'Capstone Design 14', allowedsites: ['(150) 침착맨 - Youtube 14'] },
	{ id: 15, moribsetname: 'Capstone Design 15', allowedsites: ['(150) 침착맨 - Youtube 15'] },
	{ id: 16, moribsetname: 'Capstone Design 16', allowedsites: ['(150) 침착맨 - Youtube 16'] },
	{ id: 17, moribsetname: 'Capstone Design 17', allowedsites: ['(150) 침착맨 - Youtube 17'] },
	{ id: 18, moribsetname: 'Capstone Design 18', allowedsites: ['(150) 침착맨 - Youtube 18'] },
	{ id: 19, moribsetname: 'Capstone Design 19', allowedsites: ['(150) 침착맨 - Youtube 19'] },
	{ id: 20, moribsetname: 'Capstone Design 20', allowedsites: ['(150) 침착맨 - Youtube 20'] },
];
